name: Swift Tools

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # test:
  #   runs-on: macos-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Swift
  #       uses: swift-actions/setup-swift@v2
  #       with:
  #         swift-version: '6.0'

  #     - name: Resolve dependencies
  #       run: swift package resolve

  #     - name: Run tests
  #       run: swift test

  lint:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '6.0'

      - name: Resolve dependencies
        run: swift package resolve

      - name: Lint
        run: |
          if ! command -v swiftlint &> /dev/null; then
            brew install swiftlint
          fi
          swiftlint lint --strict

  format:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '6.0'

      - name: Resolve dependencies
        run: swift package resolve

      - name: Check format
        run: |
          if ! command -v swiftformat &> /dev/null; then
            brew install swiftformat
          fi
          swiftformat --lint .
